### ISSUE TITLE
レビュー依頼

### ISSUE THREAD

**Issue by you-u-u** [you-u-u/Portfolio#165]
# レビュー依頼
## MVP以降追加した機能
- [x] LINE通知機能(毎日8時にイラストの送信)
- [x] My pageのdiary編集機能
- [x] 利用規約ページの作成
- [x] プライバシーポリシーページの作成
- [x] お問い合わせフォームの作成
- [x] TOPにアプリの使い方を表示
- [x] TOPにswiper追加
- [x] OGP設定
- [x] ファビコンの設置
- [x] 404，500エラー画面の作成
- [x] RSpecテスト(model/diary)実施
- [x] git hub action導入
　
## 追加予定機能
 - posesに対してのお気に入り機能(like_posesテーブル)
 - diary登録後のYou tube(YouTubesテーブル)表示 　(yogaをもう少し行いたい方向け)
 - カレンダーのパズル形式化(登録を行うと、その日のパネルが開き毎日登録を行うと絵が完成する)

**Comment by Tsuchiya2** [comment]
お疲れ様です！
アプリとコード拝見しました。
一定水準以上になっているかと思います！LGTMです！
以下のレビュー内容、就活と並行して取り組んでいきましょう。
（週次等の報告も終了で大丈夫です）
引き続き頑張ってください！

---

■緊急度：高
・利用規約・プライバシーポリシー・お問い合わせ等のデフォルトリンクを My Diary とかと同様の見た目にする。（行ったポーズはリンクとパッと見で分からせるという意図であればOKですが、挙げた3つは目立たせなくて良いと思いました）

・Diaryページの下部に白領域が表示されてしまわないようにする。（コンテンツ表示の部分をvh 100%になるようにしてあげると良さそうかと感じました）
![image](https://github.com/user-attachments/assets/7dccb1ce-25e3-412e-943b-62b7f56bd2b9)


・トップページの3つのコンテンツ、高さがちょっとずつ異なっているので、高さを指定して共通の高さで表示するようにする。（見た目の崩れはマイナスポイントになってしまうため）
![image](https://github.com/user-attachments/assets/9e018ff7-3804-4da9-b6f3-f75858894a34)

・個々のDiaryはidではなくUUIDとかにして、推測されにくいものにしましょう。
https://github.com/user-attachments/assets/58eaaf01-ee61-43b0-8389-294332d8a090

・コード内にあるコメントアウトされている記述を削除。（コメントやbinding.pryが残っていたりすると印象が良くないため）

・testフォルダの削除（specフォルダでテストを管理しているので削除しておきましょう）

・xxxx.Identifierファイルの削除（こちらも不要ですので削除しておきましょう）

・Diaryモデルのprivateとメソッドに空行を入れる＆余計な空白を削除する（素のRubocopが通るようにしておきましょう）

・余計なファイルの削除
- ngrok-stable-linux-amd64.zip
- ngrok-v3-stable-linux-amd64.tgz

・README.mdを就活アピール向けに改修（他の作品のREADMEやQiitaの記事などを参考にしてアピールREADMEにしておきましょう！）

■緊急度：中
・404, 500ページ：テキストだけでなくアプリケーションの世界観に合った見た目にしておきましょう。

・テストの拡充：システムテスト・モデルテストの記述を増やしていきましょう。

---

> 1. 追加機能実装後の再レビュー依頼の可否について 
当初予定のテーブル設計から変更があり、現在テーブル数はusers,poses,diariesの3つとなっております。就活を意識しissue実装予定機能を追加したうえで再度レビュー依頼を行ってもよいのでしょうか？

こちらは必要ないかと思いますので、ご自身で進めていただいて大丈夫です！

>  2. 例外キャッチの実装場所について  
以前のスケジュール面談にて、例外キャッチを導入するというお話でしたが、現在どこに入れるのが適切か判断できず実装しておりません :sweat_drops: どういった場合に入れるのがいいかアドバイスいただけると幸いです :blob_attention: 

ApplicationControllerとかで大丈夫かと思います！例外キャッチ=開発者に連絡という意味であれば、404はユーザーの入力に問題があるケースなのでスルー、500系はlogger.infoではなくもう少し高めのものにして、その直後に開発者にメールを飛ばす処理を書いて、最後にrenderで良いかと！

```ruby
  def render_500(e = nil)
    logger.info "Rendering 500 error #{e.message}" if e
    # メール送信の処理
    render "errors/500", layout: false, status: :internal_server_error
  end
```

> 3. 今後の対応について 
今後の実装において、こちらにて質問は可能でしょうか :thinking_face: 

就活に望めるだけの水準にタッチしておりますので、これまでに身に着けた自走力を活かしてサービスを改善してより良いものにしていきましょう！（就活に大きく関わるようなもの以外は、極力自分で対応いただけると助かります🙇‍♂）

**Comment by you-u-u** [comment]
ご確認ありがとうございました！
