### ISSUE TITLE
”issueベースの開発”レビュー依頼

### ISSUE THREAD

**Issue by you-u-u** [you-u-u/Portfolio#22]
# 概要

### GitHub Project
https://github.com/users/you-u-u/projects/2/views/1

### MVP
- [ ] ユーザー登録機能
- [ ] LINEログイン機能
- [ ] ログアウト機能
- [ ] LINE通知機能
- [ ] yogaポーズ提供機能
- [ ] カレンダー登録機能
- [ ] X投稿
- [ ] LINE通知機能

### 本リリース
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] アプリ内投稿機能

### 必要なページ
- [ ] トップページ
- [ ] ポーズ提供ページ
- [ ] ログインページ
- [ ] 実践ポーズ投稿ページ
- [ ] 投稿完了ページ
- [ ] 投稿編集ページ
- [ ] マイページ
- [ ] 利用規約ページ
- [ ] プライバシーポリシーページ
- [ ] お問い合わせページ
- [ ] 投稿ページ
- [ ] 投稿一覧ページ

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
以下コメントになります。

---

ストーリーポイント5のものが散見された印象でした。おそらく見通しが難しいものを5にされているのかと推測しました。1,2ポイントになるまで細分化することで、不透明箇所・明確になっている箇所が分かるだけでなく、進捗を感じながら開発を進めることができます。5ポイントのものはもう少し細分化してみましょう。

**Comment by you-u-u** [comment]
ご確認およびコメントありがとうございます。

ご指摘の通り、自分の中で解像度が低いものが多々ありました。そのため、実装の内容を確認しストーリーポイントが低くなるようissueを細分化し、整理いたしました。
再度ご確認お願いいたします。

https://github.com/users/you-u-u/projects/2/views/1

**Comment by tmtkzk0823** [comment]
確認させていただきました。
概ね良さそうです。
LGTMです！

**Comment by you-u-u** [comment]
ありがとうございます！
開発進めていきます！
よろしくお願いいたします。
