### ISSUE TITLE
MVPリリースレビュー提出

### ISSUE THREAD

**Issue by you-u-u** [you-u-u/Portfolio#97]
### サービス名
  Yoga Diary
### サービスURL
 https://www.yoga-diary-app.com/
### Git Hub
https://github.com/you-u-u/Portfolio

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [X] ユーザー登録機能(LINE認証)
- [ ] LINE通知
- [x] yogaポーズ提供機能
- [x] 日記記録・編集機能
- [x] 記録用カレンダー
- [ ] X投稿 (実践したyogaポーズをシェアする)

## READMEレビュー時から変更した機能
- [ ] LINE通知機能
- [ ] X投稿機能

※面談にて本リリース時に実装することとしましたので、今後実装いたします。

## サービスイメージがわかるようなスクリーンショット等
トップページ
[![Image from Gyazo](https://i.gyazo.com/ba22f08908661944dcb54ac8ed225e3c.png)](https://gyazo.com/ba22f08908661944dcb54ac8ed225e3c)

yogaポーズ提供機能
[![Image from Gyazo](https://i.gyazo.com/c276c33bbb7d67dbb5b3dd872cb4bd20.png)](https://gyazo.com/c276c33bbb7d67dbb5b3dd872cb4bd20)

日記記録機能
[![Image from Gyazo](https://i.gyazo.com/4b08d668ec078a1920ecf7997304c06e.png)](https://gyazo.com/4b08d668ec078a1920ecf7997304c06e)

記録用カレンダー
[![Image from Gyazo](https://i.gyazo.com/06550cfacb7dbf24d083f872c8d69e63.png)](https://gyazo.com/06550cfacb7dbf24d083f872c8d69e63)

**Comment by kashiwagi-rena** [comment]
LGTMです！
技術面でのアピール強化として、アプリ開発カリキュラムの「高度な機能」を検討してみましょう！
https://school.runteq.jp/v3/curriculums/application_development/chapters/6

使用させていただきました、14個のヨガのポーズが登録してあり、デスクワーク中心になった私にも嬉しいサービスでした。
LINEログインもスムーズに行えました。
シェア機能等今後入れる機能も楽しみにしております。

**Comment by you-u-u** [comment]
ご確認、コメントありがとうございます！
LINE通知等、「高度な機能」を本リリース時に実装したいと思います！
今後ともよろしくお願いいたします。
